name: medichive_admin_algorina
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/patient.png
    - assets/doctor.png
    - assets/lab admin.jpg
    - assets/institute admin.png
    - assets/medichive admin.jpg
    - assets/stethoscope.png
